name: camera_forma
description: An extension of the Flutter camera plugin that enables live video streaming over RTMP on Android and iOS devices.
version: 2.2.0
homepage: https://github.com/FormaIt/camera_forma

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.1.0
  video_player: ^2.7.0

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.camera_forma
        pluginClass: CameraFormaPlugin
      ios:
        pluginClass: CameraFormaPlugin
